import React from 'react';

const ReportCardFooter = ({ principalName }) => {
  return (
    <footer className="mt-12 border-t border-dashed border-gray-300 pt-8">
      <div className="grid gap-6 text-sm text-gray-600 md:grid-cols-2">
        <div className="space-y-2">
          <span className="block h-12 border-b-2 border-dashed border-gray-300"></span>
          <p className="font-semibold text-gray-900">{principalName || "Principal's Signature"}</p>
          <p className="text-xs uppercase tracking-[0.3em] text-gray-400">Principal</p>
        </div>
        <div className="space-y-2">
          <span className="block h-12 border-b-2 border-dashed border-gray-300"></span>
          <p className="font-semibold text-gray-900">Class Teacher's Signature</p>
          <p className="text-xs uppercase tracking-[0.3em] text-gray-400">Class Teacher</p>
        </div>
      </div>
      <p className="mt-8 text-center text-xs uppercase tracking-[0.4em] text-gray-400">Generated by ReportSheet</p>
    </footer>
  );
};

export default ReportCardFooter;