// This file contains non-AI based fallbacks for generating content when offline.

interface CommentContext {
    studentName: string;
    performanceSummary: string;
    // Future context can be added here, e.g., subjectName, score
}

export const generateFallbackComment = (context: CommentContext): string => {
    const { studentName, performanceSummary } = context;
    const performanceLower = performanceSummary.toLowerCase();
    
    let opening = `${studentName} has demonstrated a positive attitude towards learning.`;
    let detail = '';
    let recommendation = 'Continued effort will surely yield even better results.';

    // Analyze performance summary for keywords
    if (performanceLower.includes('excellent') || performanceLower.includes('strong') || performanceLower.includes('very good')) {
        opening = `${studentName} has shown excellent performance this term.`;
        detail = 'He/She consistently submits high-quality work and actively participates in class discussions.';
        recommendation = 'Keep up the fantastic work!';
    } else if (performanceLower.includes('good') || performanceLower.includes('steady progress')) {
        opening = `${studentName} is making steady progress.`;
        detail = 'He/She grasps new concepts well with consistent effort.';
    } else if (performanceLower.includes('struggles') || performanceLower.includes('difficulty') || performanceLower.includes('weak')) {
        opening = `${studentName} shows potential but is facing some challenges.`;
        detail = 'He/She sometimes struggles with new topics but is encouraged to ask more questions in class.';
        recommendation = 'With increased focus and consistent practice, improvement is definitely achievable.';
    } else if (performanceLower.includes('improvement')) {
        opening = `${studentName} has shown commendable improvement this term.`;
        detail = 'His/Her hard work is beginning to pay off, which is wonderful to see.';
    }

    return [opening, detail, recommendation].filter(Boolean).join(' ');
};

// You can add more fallback functions here, e.g., for lesson planning
export const getFallbackLessonPlan = (topic: string) => {
    return `A lesson plan for "${topic}" could not be generated by the AI while offline.

    Here is a basic template you can use:
    1. Instructional Objectives: Define what students will learn.
    2. Materials: List required items.
    3. Procedure: Outline your teaching steps.
    4. Evaluation: Plan how to check for understanding.
    5. Assignment: Give relevant homework.
    `;
};

export const getFallbackChatResponse = (prompt: string): string => {
    const p = prompt.toLowerCase();
    if (p.includes('add') && (p.includes('student') || p.includes('teacher'))) {
        return "To add a new student or teacher, please navigate to the 'Students' or 'Teachers' page from the main menu and click the 'Add' button.";
    }
    if (p.includes('score') || p.includes('result')) {
        return "You can enter student scores on the 'Enter Scores' page, accessible from the 'Academics' section in the sidebar.";
    }
    if (p.includes('report card')) {
        return "Report cards can be generated, viewed, and printed from the 'Report Cards' page in the 'Academics' section.";
    }
    if (p.includes('timetable') || p.includes('schedule')) {
        return "The school timetable can be managed from the 'Timetable' page. You can view your personal schedule as a teacher from your dashboard.";
    }
    return "I have limited functionality while offline. I can only answer basic questions about navigating the app. Please connect to the internet for full assistance.";
};

export const getFallbackTutorResponse = (prompt: string): string => {
    return "I'm sorry, I cannot provide detailed academic explanations while you are offline. My full capabilities, including explaining complex topics and providing practice exercises, require an internet connection. Please try again when you're online.";
};
