// This file contains the original, simple fallback logic before the major overhaul.
// It is imported by the new `fallbackAiService.ts` to maintain backward compatibility for specific functions.

interface CommentContext {
    studentName: string;
    performanceSummary: string;
}

export const generateFallbackComment = (context: CommentContext): string => {
    const { studentName, performanceSummary } = context;
    const performanceLower = performanceSummary.toLowerCase();
    
    let opening = `${studentName} has demonstrated a positive attitude towards learning.`;
    let detail = '';
    let recommendation = 'Continued effort will surely yield even better results.';

    if (performanceLower.includes('excellent') || performanceLower.includes('strong') || performanceLower.includes('very good')) {
        opening = `${studentName} has shown excellent performance this term.`;
        detail = 'He/She consistently submits high-quality work and actively participates in class discussions.';
        recommendation = 'Keep up the fantastic work!';
    } else if (performanceLower.includes('good') || performanceLower.includes('steady progress')) {
        opening = `${studentName} is making steady progress.`;
        detail = 'He/She grasps new concepts well with consistent effort.';
    } else if (performanceLower.includes('struggles') || performanceLower.includes('difficulty') || performanceLower.includes('weak')) {
        opening = `${studentName} shows potential but is facing some challenges.`;
        detail = 'He/She sometimes struggles with new topics but is encouraged to ask more questions in class.';
        recommendation = 'With increased focus and consistent practice, improvement is definitely achievable.';
    } else if (performanceLower.includes('improvement')) {
        opening = `${studentName} has shown commendable improvement this term.`;
        detail = 'His/Her hard work is beginning to pay off, which is wonderful to see.';
    }

    return [opening, detail, recommendation].filter(Boolean).join(' ');
};

export const getFallbackLessonPlan = (topic: string) => {
    return `A lesson plan for "${topic}" could not be generated by the AI while offline.

    Here is a basic template you can use:
    1. Instructional Objectives: Define what students will learn.
    2. Materials: List required items.
    3. Procedure: Outline your teaching steps.
    4. Evaluation: Plan how to check for understanding.
    5. Assignment: Give relevant homework.
    `;
};

export const getFallbackTutorResponse = (prompt: string): string => {
    return "I'm sorry, I cannot provide detailed academic explanations while you are offline. My full capabilities, including explaining complex topics and providing practice exercises, require an internet connection. Please try again when you're online.";
};

export const getFallbackParentChatResponse = (prompt: string): string => {
    return "I have limited functionality while you're offline. I can't provide detailed analysis of your child's performance right now. Please connect to the internet to ask specific questions about their progress.";
};
